backend:
  name: github
  repo: hang-ya/geek-blog
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "摘要", name: "description", widget: "text" }
      - { label: "标签", name: "tags", widget: "list", default: ["随笔"] }
      - { label: "草稿", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "正文", name: "body", widget: "markdown" }
